
export const metadata = {
  title: 'NGL',
  description: 'Generated by Toxiic',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
